apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: krw-bootcamp
  labels:
    app: krwApp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: krwApp
      tier: web
  template:
    metadata:
      labels:
        app: krwApp
        tier: web
    spec:
      containers:
      - name: test-app
        image: sky45/krwboot:v1
        ports:
        - containerPort: 80